[[chapter3]]
== Packet Encapsulation for E-Trace

<<chapter2>> describes the packet encapsulation in general terms.  This chapter describes how that applies in the context of E-Trace.

The https://github.com/riscv-non-isa/tg-nexus-trace/blob/master/pdfs/RISC-V-Trace-Control-Interface.pdf[RISC-V Trace Control Interface Specification] includes several fields relevant for the construction and synchronization of packets, as described in the following sections. 

=== *srcID*

* *trTeInhibitSrc* in the _trTeControl_ register of a trace encoder indicates whether a *srcID* is present or absent in the encapsulated packets;
* *trTeSrcBits* in the _trTeInstFeatures_ register indicates the length of the *srcID*;
* *trTeSrcID* in the _trTeInstFeatures_ register indicates the value of the *srcID* associated with that particular source.

=== *timestamp*

* When *trTsEnable* in the _trTsControl_ register is 1, a timestamp may be optionally included, via the *timestamp* field in the encapsulated packets.  When present, *header.extend* will be 1 as described in <<_section_Timestamp>>;
* *trTsWidth* in the _trTsControl_ register indicates the number of bits in *timestamp* fields.  

Note that some E-Trace packets may optionally include a *time* field, as an alternative method of providing time information.  Presence or absence of this is fixed for a given system based on a discoverable parameter, but is not run-time configurable.

=== *type*

For E-Trace, the *type* field in the *payload* group is 2 bits long with the following encodings defined:

* 10: Instruction trace packet
* 11: Data trace packet

=== Synchronization

* *trPibAsyncFreq*, *trRamAsyncFreq* and *trAtbBridgeAsyncFreq* in the _trPibControl_, _trRamControl_ and _trAtbBridgeControl_ registers respectively are used to determine the interval between insertion of synchronization sequences.

