[[intro]]
== Introduction

The https://github.com/riscv-non-isa/riscv-trace-spec/releases/download/v2.0rc2/riscv-trace-spec.pdf[Efficient Trace for RISC-V] (E-trace) standard defines packet payloads for instruction and data trace but does not fully define how this should be encapsulated for transport, nor how instruction and data trace should be differentiated.  Chapter 7 gives some illustrative examples but this is insufficiently detailed and informative only.

Although the primary motivation for developing this standard was to define an encapsulation format for E-Trace packets, the encapsulation format defined in this document is agnostic to the packet payload structure and meaning and so can be used for any kind of data.  In addition to processor trace, it could also be used for a wide variety of other uses, for example: performance counter metrics, trace or other diagnostic data from a bus fabric monitor or on-chip logic analyser. 

This specification defines an encapsulation format suitable for use with a variety of transport mechanisms, including but not limited to AMBA Advanced Trace Bus (ATB) and Siemens' Messaging Infrastructure.

=== Glossary

* *ATB* - Advanced Trace Bus, a protocol described in ARM document IHI0032B;
* *E-Trace* - Abbreviation for https://github.com/riscv-non-isa/riscv-trace-spec/releases/download/v2.0rc2/riscv-trace-spec.pdf[Efficient Trace for RISC-V];
* *PIB* - Pin Interface Block, a parallel or serial off-chip trace port feeding into a trace probe;
* *Trace Encoder* - Hardware module that accepts execution information from a hart and generates a stream of trace packets;
* *TFP* - Trace Formatter protocol, a trace framing protocol described in ARM document IHI0029E.  Also adopted by MIPI as Trace Wrapper Protocol (TWP);
* *TWP* - See *TFP*.

